### ISSUE TITLE
Small grammar things

### ISSUE THREAD

**Issue by Kevinw97** [jyoo980/open-aop#13]
https://github.com/jyoo980/open-aop/blob/6602977d2fbad65695dd8ac0e813a89621667c26/background-report/background-report.tex#L102
"... to specify what behaviour program should ..." should maybe be "to specify what behaviour programs should"

https://github.com/jyoo980/open-aop/blob/6602977d2fbad65695dd8ac0e813a89621667c26/background-report/background-report.tex#L157

Should this be "Advice in AspectJ is compactly describe in the informal EBNF below" ?

https://github.com/jyoo980/open-aop/blob/6602977d2fbad65695dd8ac0e813a89621667c26/background-report/background-report.tex#L163

Maybe capitalize Advice here, if it's a new sentence

https://github.com/jyoo980/open-aop/blob/6602977d2fbad65695dd8ac0e813a89621667c26/background-report/background-report.tex#L345
Maybe should be "reasoning about the nature of a program"

**Comment by tony-kong** [comment]
Addressed all on overleaf ill wait for james to push

**Comment by jyoo980** [comment]
Fixed in
https://github.com/jyoo980/open-aop/pull/15
