### ISSUE TITLE
Gregor google talk

### ISSUE THREAD

**Issue by raymondsitu** [jyoo980/open-aop#14]
https://github.com/jyoo980/open-aop/blob/6602977d2fbad65695dd8ac0e813a89621667c26/background-report/background-report.tex#L444

If I recall correctly we mentioned we should include it as a source

**Comment by jyoo980** [comment]
@raymondsitu where in the report do we mention it?

**Comment by raymondsitu** [comment]
@jyoo980 the observer design pattern example is from the talk. Or is that generic enough that we don't have to cite?

**Comment by jyoo980** [comment]
@raymondsitu nah I'll make a citation and cite it in the latex as well. Good catch.

**Comment by jyoo980** [comment]
Fixed in
https://github.com/jyoo980/open-aop/pull/15
