### ISSUE TITLE
Capitalization of Pointcut/Join point/Advice 

### ISSUE THREAD

**Issue by tony-kong** [jyoo980/open-aop#5]
Looking at the eclipse specification docs:
http://www.eclipse.org/aspectj/doc/next/progguide/language-joinPoints.html
https://www.eclipse.org/aspectj/doc/next/progguide/semantics-advice.html

We don't capitalize these language semantics and use them like "Names".  We just treat them normally and use it without capitalization, "advice, pointcut, join point".

I modified some of it on overleaf already but not everything.

**Comment by jyoo980** [comment]
Resolved, see 
https://github.com/jyoo980/open-aop/pull/10
